#!/bin/bash

source menu.sh
apacheInstall
apacheStart
apacheTest
personalIndex
createVirtualHost
phpInstall
instalandoPaquetesUbuntuLagunTest
creandoEntornoVirtualPython3
instalandoLibreriasPythonLagunTest
instalandoAplicacionLagunTest
pasoPropiedad
comprobarWebprocess
